"""
Generate LaTeX macros for significance test results.

Reads artifacts/stats/significance_table.csv and generates
paper/significance_values.tex with formatted values for main.tex inclusion.

This enables dynamic metric incorporation without manual hardcoding.

Usage:
    python scripts/generate_significance_tex.py
    python scripts/generate_significance_tex.py <csv_path> <output_path>
"""

import argparse
import csv
import sys
from pathlib import Path

def format_value(value):
    """Format p-value with appropriate precision and notation."""
    try:
        fval = float(value)
        if fval < 0.001:
            return "< 0.001"
        elif fval < 0.01:
            return f"{fval:.3f}"
        else:
            return f"{fval:.4f}"
    except (ValueError, TypeError):
        return str(value)

def format_accuracy_diff(value):
    """Format accuracy difference as percentage."""
    try:
        fval = float(value)
        return f"{abs(fval):.3f}"
    except (ValueError, TypeError):
        return str(value)

def generate_macros(csv_path: str, output_path: str) -> bool:
    """
    Generate LaTeX macro file from significance test results.
    
    Args:
        csv_path: Path to significance_table.csv
        output_path: Path to output significance_values.tex
    
    Returns:
        True if successful, False otherwise
    """
    csv_file = Path(csv_path)
    if not csv_file.exists():
        print(f"[ERROR] CSV file not found: {csv_file}", file=sys.stderr)
        return False
    
    # Read CSV
    results = {}
    try:
        with open(csv_file, 'r', encoding='utf-8', newline='') as f:
            reader = csv.DictReader(f)
            for row in reader:
                baseline = row['baseline'].strip()
                # Store by original name
                results[baseline] = {
                    'baseline': baseline,
                    'accuracy_diff': float(row['accuracy_diff']),
                    'mcnemar_p': float(row['mcnemar_p']),
                    'perm_p': float(row['perm_p']),
                }
    except Exception as e:
        print(f"[ERROR] Failed to read CSV: {e}", file=sys.stderr)
        return False
    
    # Generate LaTeX macros
    macros = [
        "% Auto-generated by scripts/generate_significance_tex.py",
        "% DO NOT EDIT MANUALLY - regenerate via scripts/generate_significance_tex.py",
        "% Generated from: artifacts/stats/significance_table.csv",
        ""
    ]
    
    # Map baseline names from CSV to LaTeX macro identifiers
    baseline_mapping = [
        ('Retrieval_NLI', 'Retrieval+NLI', 'RetrievalNLI'),
        ('Retrieval', 'Retrieval', 'Retrieval'),
        ('Baseline', 'Baseline', 'Baseline'),
    ]
    
    for csv_name, display_name, macro_suffix in baseline_mapping:
        # Find matching result
        result = results.get(csv_name)
        
        if result:
            acc_diff = format_accuracy_diff(result['accuracy_diff'])
            mcnemar_p = format_value(result['mcnemar_p'])
            perm_p = format_value(result['perm_p'])
            
            macros.append(f"% {display_name}")
            macros.append(f"\\newcommand{{\\SigAccDiff{macro_suffix}}}{{{acc_diff}}}")
            macros.append(f"\\newcommand{{\\SigPvalMcNemar{macro_suffix}}}{{{mcnemar_p}}}")
            macros.append(f"\\newcommand{{\\SigPvalPermutation{macro_suffix}}}{{{perm_p}}}")
            macros.append("")
        else:
            print(f"[WARN] Baseline '{csv_name}' not found in CSV", file=sys.stderr)
    
    # Write output
    output_file = Path(output_path)
    try:
        with open(output_file, 'w', encoding='utf-8', newline='') as f:
            f.write('\n'.join(macros))
        print(f"[OK] Generated {output_file}")
        return True
    except Exception as e:
        print(f"[ERROR] Failed to write output: {e}", file=sys.stderr)
        return False

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate LaTeX macros from significance test CSV"
    )
    parser.add_argument(
        "csv_path",
        nargs="?",
        default="artifacts/stats/significance_table.csv",
        help="Path to significance_table.csv (default: artifacts/stats/significance_table.csv)"
    )
    parser.add_argument(
        "output_path",
        nargs="?",
        default="paper/significance_values.tex",
        help="Path to output significance_values.tex (default: paper/significance_values.tex)"
    )
    
    args = parser.parse_args()
    
    if not generate_macros(args.csv_path, args.output_path):
        sys.exit(1)
    sys.exit(0)
