#!/usr/bin/env python3
"""Deterministic verification for reported calibration/selective-prediction metrics.

Reads canonical prediction artifacts:
  artifacts/preds/*.npz
Computes per-model metrics and writes:
  artifacts/metrics_summary.json
  artifacts/metrics_summary.md
  artifacts/verification_report.md
  submission_bundle/metrics_values.tex

Supports deterministic comparison:
  python scripts/verify_reported_metrics.py --compare artifacts/metrics_summary.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.eval.metrics import compute_accuracy_coverage_curve, compute_auc_ac, compute_ece


TABLE_ECE_PATTERN = re.compile(r"ECE\s*&\s*([0-9]+\.[0-9]+)")
TABLE_AUC_PATTERN = re.compile(r"AUC-AC\s*&\s*([0-9]+\.[0-9]+)")


def _load_npz(path: Path) -> Tuple[np.ndarray, np.ndarray]:
    data = np.load(path, allow_pickle=True)
    if "y_true" not in data or "probs" not in data:
        raise ValueError(f"{path} missing required arrays y_true/probs")
    y_true = np.asarray(data["y_true"], dtype=np.int64)
    probs = np.asarray(data["probs"], dtype=np.float64)
    if y_true.ndim != 1 or probs.ndim != 1:
        raise ValueError(f"{path} arrays must be 1D")
    if len(y_true) != len(probs):
        raise ValueError(f"{path} length mismatch y_true/probs")
    return y_true, np.clip(probs, 0.0, 1.0)


def _macro_f1_binary(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    values: List[float] = []
    for cls in (0, 1):
        tp = int(np.sum((y_pred == cls) & (y_true == cls)))
        fp = int(np.sum((y_pred == cls) & (y_true != cls)))
        fn = int(np.sum((y_pred != cls) & (y_true == cls)))
        p = tp / (tp + fp) if (tp + fp) else 0.0
        r = tp / (tp + fn) if (tp + fn) else 0.0
        values.append(0.0 if (p + r) == 0.0 else (2.0 * p * r / (p + r)))
    return float(np.mean(values))


def _compute_model_metrics(y_true: np.ndarray, probs: np.ndarray) -> Dict:
    ece_result = compute_ece(
        y_true=y_true,
        probs_or_logits=probs,
        n_bins=10,
        scheme="equal_width",
        confidence_mode="predicted_class",
    )
    curve = compute_accuracy_coverage_curve(
        y_true=y_true,
        probs_or_logits=probs,
        confidence_mode="predicted_class",
        thresholds="unique",
    )
    auc_ac = compute_auc_ac(curve["coverage"], curve["accuracy"])

    pred = (probs >= 0.5).astype(np.int64)
    acc = float(np.mean(pred == y_true))
    macro_f1 = _macro_f1_binary(y_true, pred)

    return {
        "accuracy": acc,
        "ece": float(ece_result["ece"]),
        "auc_ac": float(auc_ac),
        "macro_f1": macro_f1,
        "ece_bins": ece_result["bins"],
        "accuracy_coverage_curve": curve,
    }


def _extract_manuscript_values(tex_path: Path) -> Dict[str, float]:
    if not tex_path.exists():
        return {}
    text = tex_path.read_text(encoding="utf-8", errors="ignore")
    ece_match = TABLE_ECE_PATTERN.search(text)
    auc_match = TABLE_AUC_PATTERN.search(text)
    values: Dict[str, float] = {}
    if ece_match:
        values["ece"] = float(ece_match.group(1))
    if auc_match:
        values["auc_ac"] = float(auc_match.group(1))
    return values


def _as_table_markdown(summary: Dict) -> str:
    lines = [
        "# Metrics Summary (Deterministic)",
        "",
        "| Model | N | Accuracy | ECE | AUC-AC | Macro-F1 |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for model_name in sorted(summary["models"].keys()):
        item = summary["models"][model_name]
        lines.append(
            f"| {model_name} | {item['n_samples']} | {item['accuracy']:.4f} | {item['ece']:.4f} | {item['auc_ac']:.4f} | {item['macro_f1']:.4f} |"
        )

    primary = summary["primary_model"]
    p = summary["models"][primary]
    lines += [
        "",
        f"Primary model: **{primary}**",
        f"- Accuracy: {p['accuracy']:.4f}",
        f"- ECE: {p['ece']:.4f}",
        f"- AUC-AC: {p['auc_ac']:.4f}",
    ]
    return "\n".join(lines) + "\n"


def _write_metric_macros(output_tex: Path, accuracy: float, ece: float, auc_ac: float) -> None:
    output_tex.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "% Auto-generated by scripts/verify_reported_metrics.py\n"
        f"\\newcommand{{\\AccuracyValue}}{{{accuracy*100:.2f}\\%}}\n"
        f"\\newcommand{{\\ECEValue}}{{{ece:.4f}}}\n"
        f"\\newcommand{{\\AUCACValue}}{{{auc_ac:.4f}}}\n"
    )
    output_tex.write_text(content, encoding="utf-8")


def _compare_summaries(current: Dict, baseline: Dict, tol: float = 1e-6) -> List[str]:
    errors: List[str] = []
    current_models = current.get("models", {})
    baseline_models = baseline.get("models", {})

    if sorted(current_models.keys()) != sorted(baseline_models.keys()):
        errors.append("Model set differs between current and baseline summaries")
        return errors

    for model in sorted(current_models.keys()):
        for metric in ("accuracy", "ece", "auc_ac", "macro_f1"):
            a = float(current_models[model][metric])
            b = float(baseline_models[model][metric])
            if abs(a - b) > tol:
                errors.append(f"{model}.{metric}: {a:.10f} != {b:.10f}")
    return errors


def build_summary(preds_dir: Path, primary_model: str | None) -> Dict:
    npz_files = sorted(preds_dir.glob("*.npz"))
    if not npz_files:
        raise FileNotFoundError(f"No .npz files found in {preds_dir}")

    models: Dict[str, Dict] = {}
    for path in npz_files:
        y_true, probs = _load_npz(path)
        metrics = _compute_model_metrics(y_true, probs)
        model_name = path.stem
        models[model_name] = {
            "source": str(path).replace("\\", "/"),
            "n_samples": int(len(y_true)),
            **metrics,
        }

    chosen_primary = primary_model
    if not chosen_primary:
        chosen_primary = "CalibraTeach" if "CalibraTeach" in models else sorted(models.keys())[0]
    if chosen_primary not in models:
        raise ValueError(f"Primary model '{chosen_primary}' not found in {preds_dir}")

    manuscript_values = _extract_manuscript_values(Path("submission_bundle/OVERLEAF_TEMPLATE.tex"))
    primary_metrics = models[chosen_primary]

    stale_check = {
        "manuscript_table_ece": manuscript_values.get("ece"),
        "manuscript_table_auc_ac": manuscript_values.get("auc_ac"),
        "computed_primary_ece": primary_metrics["ece"],
        "computed_primary_auc_ac": primary_metrics["auc_ac"],
        "matches_table_values": (
            manuscript_values.get("ece") is not None
            and manuscript_values.get("auc_ac") is not None
            and abs(primary_metrics["ece"] - manuscript_values["ece"]) <= 1e-6
            and abs(primary_metrics["auc_ac"] - manuscript_values["auc_ac"]) <= 1e-6
        ),
        "legacy_figure_annotation_values": {"ece": 0.0092, "auc_ac": 0.6962},
    }

    return {
        "metadata": {
            "ece": {
                "n_bins": 10,
                "scheme": "equal_width",
                "confidence_mode": "predicted_class",
            },
            "auc_ac": {
                "integration": "trapezoidal",
                "range": "[0,1]",
            },
        },
        "primary_model": chosen_primary,
        "models": models,
        "consistency_check": stale_check,
    }


def write_verification_report(path: Path, summary: Dict, compare_errors: List[str]) -> None:
    primary = summary["primary_model"]
    p = summary["models"][primary]
    consistent = summary["consistency_check"]["matches_table_values"]

    lines = [
        "# Verification Report",
        "",
        "## Commands Executed",
        "",
        "- python scripts/export_predictions_npz.py",
        "- python scripts/verify_reported_metrics.py",
        "- python scripts/generate_paper_figures.py",
        "- python scripts/verify_reported_metrics.py --compare artifacts/metrics_summary.json",
        "",
        "## Final Metric Values (Primary)",
        "",
        f"- Model: {primary}",
        f"- Accuracy: {p['accuracy']:.4f}",
        f"- ECE: {p['ece']:.4f}",
        f"- AUC-AC: {p['auc_ac']:.4f}",
        f"- Macro-F1: {p['macro_f1']:.4f}",
        "",
        "## Consistency Status",
        "",
        f"- Manuscript table matches computed values: {'YES' if consistent else 'NO'}",
        "- Figures are generated from metrics_summary.json and per-example predictions.",
        "- Captions/text should use generated LaTeX macros from submission_bundle/metrics_values.tex.",
        "",
    ]

    if compare_errors:
        lines += ["## Deterministic Compare", "", "FAIL", ""]
        lines.extend([f"- {e}" for e in compare_errors])
    else:
        lines += ["## Deterministic Compare", "", "PASS", "", "- Re-run matches baseline within tolerance 1e-6."]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Verify reported metrics deterministically")
    parser.add_argument("--preds_dir", type=Path, default=Path("artifacts/preds"))
    parser.add_argument("--output_dir", type=Path, default=Path("artifacts"))
    parser.add_argument("--primary_model", type=str, default=None)
    parser.add_argument("--compare", type=Path, default=None)
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    summary = build_summary(args.preds_dir, args.primary_model)

    json_path = args.output_dir / "metrics_summary.json"
    md_path = args.output_dir / "metrics_summary.md"
    report_path = args.output_dir / "verification_report.md"

    json_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    md_path.write_text(_as_table_markdown(summary), encoding="utf-8")

    primary = summary["primary_model"]
    p = summary["models"][primary]
    _write_metric_macros(
        Path("submission_bundle/metrics_values.tex"),
        accuracy=p["accuracy"],
        ece=p["ece"],
        auc_ac=p["auc_ac"],
    )

    compare_errors: List[str] = []
    if args.compare:
        baseline = json.loads(args.compare.read_text(encoding="utf-8"))
        compare_errors = _compare_summaries(summary, baseline, tol=1e-6)

    write_verification_report(report_path, summary, compare_errors)

    print(f"[OK] Wrote {json_path}")
    print(f"[OK] Wrote {md_path}")
    print(f"[OK] Wrote {report_path}")
    print("[OK] Wrote submission_bundle/metrics_values.tex")
    print(f"Primary={primary} ECE={p['ece']:.4f} AUC-AC={p['auc_ac']:.4f}")

    if compare_errors:
        for err in compare_errors:
            print(f"[DIFF] {err}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
